library("phyloseq");packageVersion("phyloseq")
library(ape)
otu <- read.table("biom_iodamoeba.txt", sep="\t", header=T, row.names=1)
otu <- as.matrix(otu)
map <- as.matrix(read.table("map.txt", sep="\t", header=T, row.names=1))
tre <- read.tree("RAxML_bipartitions.iodamoeba.tre")
tre <- root(tre, outgroup="JN635740.1")
otutable <- otu_table(otu, taxa_are_rows=T)
physeq <- phyloseq(otutable)
physeq <- merge_phyloseq(physeq, tre, map)

pdf("iodamoeba_phyloseq_tree.pdf")
plot_tree(physeq, color="Sample", ladderize="right", label.tips="taxa_names", nodelabf=nodeplotboot(50,50))
dev.off()

#now make phylotree of the entamoeba stuff
library("phyloseq");packageVersion("phyloseq")
library(ape)
library(ggplot2)
otu <- read.table("biom.txt", sep="\t", header=T, row.names=1)
otu <- as.matrix(otu)
map <- as.data.frame(read.table("map.txt", sep="\t", header=T, row.names=1))
tre <- read.tree("../RAxML_bipartitions.entamoeba.trim.tre")
otutable <- otu_table(otu, taxa_are_rows=T)
map <- sample_data(map)
physeq <- phyloseq(otutable)
physeq <- merge_phyloseq(physeq, tre, map)

pdf("entamoeba_phyloseq_tree_shapes.pdf")
plot_tree(physeq, color="Phyl_Group", shape="Genus", ladderize="right", label.tips="taxa_names", nodelabf=nodeplotboot(50,50)) + scale_shape_manual(values=1:13)
dev.off()

pdf("entamoeba_phyloseq_tree.pdf")
plot_tree(physeq, color="Genus", ladderize="right", label.tips="taxa_names", nodelabf=nodeplotboot(50,50))
dev.off()