######################
#Iodamoeba clustering
######################
#first pull iodamoeba otu ids that made it into the placement tree, filter from representative set
cd /parfreylab/mann/primateEuk
mkdir iodamoeba_heatmap
grep "denovo" eukref_trees/archamoeba_placement/htes_aligned_iodamoeba/iodamoeba.denovo_aligned.plus_curated_pfiltered.fasta | sed 's/>//' > iodamoeba_heatmap/ids
cd iodamoeba_heatmap

############NOTE: NEED TO GET OVERLAP BETWEEN FILTERED DATASET AND THOSE THAT MADE IT INTO IODAMOEBA PLACEMENT TREE
cat ids post_filter.ids | sort | uniq -c | grep "2 " | awk '{print $2}' > filtered_ids
filter_fasta.py -f iodamoeba.fa -o filtered.fa -s filtered_ids

#now add in reference iodamoeba sequences and align
grep "Ioda" ../eukref_trees/archamoeba_reference/reference.amoeba.fa | awk '{print $1}' | sed 's/>//' > refids
filter_fasta.py -f /parfreylab/mann/primateEuk/eukref_trees/archamoeba_reference/reference.amoeba.fa -s refids -o refs.fa
cat iodamoeba.fa refs.fa > full.fa
mafft --auto full.fa > align.fa

#clean up alignment
trimal -in align.fa -out align.trimal.fa -gt 0.99 -st 0.001
sed 's/ .*//' align.trimal.fa > align.clean.fa
#open in aliviewer, remove sequences that are too short for proper alignment, now everything down to 171 bp
#dereplicate so that reads that are now identical are removed

#build tree
#scp align.trimal.fa align.clean.fa mann@zoology.ubc.ca:/parfreylab/mann/primateEuk/iodamoeba_heatmap
raxmlHPC-PTHREADS-SSE3 -T 4 -m GTRCAT -c 25 -e 0.001 -p 31414 -f a -N 100 -x 02938 -n tre -s align.trimal.fa

#build tree with reduced (duplicate removed) file generated by raxml
#raxmlHPC-PTHREADS-SSE3 -T 4 -m GTRCAT -c 25 -e 0.001 -p 31414 -f a -N 100 -x 02938 -n dedup.tre -s align.clean.fa.reduced

#fix reduced file
scp mann@zoology.ubc.ca:/parfreylab/mann/primateEuk/iodamoeba_heatmap/*reduced* .
sed -i 's/^/>/' align.clean.fa.reduced
sed -i 's/ /\n/' align.clean.fa.reduced

#want to get a distance matrix in r
library(ape)
library(RColorBrewer)
library(gplots)
align <- read.dna("align.clean.fa.reduced", format="fasta")
#Kimura 1980 distance calculation, considers transitions/transversion as diff probability
mat <- dist.dna(align, as.matrix=TRUE, model="K80")
tree <- read.tree("RAxML_bipartitions.dedup.ordered.tre")
tree <- root(tree, outgroup="JN635740.1")
neworder <- tree$tip.label
mat <- mat[neworder,neworder]
pal <- colorRampPalette(rev(brewer.pal(10, 'YlOrRd')))
pdf("iodamoeba_dist_heatmap.pdf")
heatmap.2(mat, symm=T, col=pal(9), key=TRUE, density.info="none", trace="none")
dev.off()

